cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartView.as_view(), name="cart_view"),
    url(r'^dodaj/(?P<pk>\d+)/$', views.AddToCartView.as_view(), name="add_to_cart_view"),
    url(r'^usun/(?P<pk>\d+)/$', views.RemoveFromCartView.as_view(), name="remove_from_cart_view"),
]

swietlny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from news.views import NotFoundView

urlpatterns = [
    url(r'', include('news.urls', namespace="news")),
    url(r'^produkty/', include('products.urls', namespace="products")),
    url(r'^uzytkownicy/', include('users.urls', namespace="users")),
    url(r'^koszyk/', include('cart.urls', namespace="cart")),
    url(r'^zamowienia/', include('orders.urls', namespace="orders")),
    url(r'^admin/', admin.site.urls),
]

handler404 = NotFoundView.as_view()

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,10)]


class CartUpdateProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, 
                                        coerce=int)
    update = forms.BooleanField(required=False, initial=False, 
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

from products.models import Product
from .cart import Cart
from .forms import CartUpdateProductForm


class AddToCartView(View):
    def post(self, request, pk):
        cart = Cart(request)
        product = Product.active_objects.get(pk=pk)
        cart_form = CartUpdateProductForm(request.POST)
        if cart_form.is_valid():
            cleaned_data = cart_form.cleaned_data
            cart.add(product=product,
                        quantity=cleaned_data['quantity'],
                        update_quantity=cleaned_data['update'])
        return redirect('cart:cart_view')
        
        
class RemoveFromCartView(View):
    def post(self, request, pk):
        cart = Cart(request)
        product = Product.active_objects.get(pk=pk)
        cart.remove(product)
        return redirect('cart:cart_view')
        

class CartView(View):
    template = 'cart/cart_detail.html'
    def get(self, request):
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form'] = CartUpdateProductForm(initial={
                'quantity': item['quantity'], 'update': True
            })
        context = {
            'cart': cart
        }
        return render(request, self.template, context)

cart/templates/cart/cart_detail.html
{% extends "base.html" %} {% block head_title %}Koszyk{% endblock %} {% block content %} {% load staticfiles %} {% load mathfilters %}

<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>Koszyk</li>
            </ul>
        </div>

        <div class="col-md-9" id="basket">

            <div class="box">

                    <h1>Koszyk</h1>
                    <p class="text-muted">Ilość produktów w koszyku: {{cart|length}} </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th colspan="3">Produkt</th>
                                    <th>Ilość</th>
                                    <th>Cena za 1 szt.</th>
                                    <th colspan="2">Suma</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for item in cart %}
                                <tr>
                                    <td>
                                        <a href="{% url 'products:product_view' pk=item.product.pk %}">
                                            <img src="{{item.product.images.0.image.url}}" alt="{{item.product.title}}">
                                        </a>
                                    </td>
                                    <td><a href="{% url 'products:product_view' pk=item.product.pk %}">{{item.product.title}}</a>
                                    </td>
                                    <td></td>
                                    <td>
                                        <form action="{% url 'cart:add_to_cart_view' pk=item.product.pk %}" method="POST">
                                            {% csrf_token %}
                                            {{ item.update_quantity_form.quantity }} 
                                            {{ item.update_quantity_form.update }}
                                            <button type="submit" class="btn btn-blank"><i class="fa fa-refresh"></i></button>
                                        </form>
                                    </td>
                                    <td>{{item.price}} zł</td>
                                    <td>{{item.total_price}} zł</td>
                                    <td>
                                        <form action="{% url 'cart:remove_from_cart_view' pk=item.product.pk %}" method="POST">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-blank"><i class="fa fa-trash-o"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                                
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="5">Razem</th>
                                    <th colspan="2">{{cart.get_total_price}} zł</th>
                                </tr>
                            </tfoot>
                        </table>

                    </div>
                    <!-- /.table-responsive -->

                    <div class="box-footer">
                        <div class="pull-left">
                            {% if cart|length > 0 %}
                            {% with cart|last as last_item %}
                            <a href="{% url 'products:category_view' category_slug=last_item.product.categories.all.0.slug %}" class="btn btn-default btn-md"><i class="fa fa-chevron-left"></i> Kontynuuj zakupy</a>
                            {% endwith %}
                            {% else %}
                            <a href="{% url 'news:home' %}" class="btn btn-default btn-md"><i class="fa fa-chevron-left"></i> Kontynuuj zakupy</a>
                            {% endif %}
                        </div>
                        <div class="pull-right">
                            <a href="{% url 'orders:order_create_view' %}" class="btn btn-primary">Złóż zamówienie <i class="fa fa-chevron-right"></i>
                            </a>
                        </div>
                    </div>

            </div>
            <!-- /.box -->


        </div>
        <!-- /.col-md-9 -->

        <div class="col-md-3">
            {% include 'order-summary.html' %}

        </div>
        <!-- /.col-md-3 -->

    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}