cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartView.as_view(), name="cart_view"),
    url(r'^dodaj/(?P<pk>\d+)/$', views.AddToCartView.as_view(), name="add_to_cart_view"),
    url(r'^usun/(?P<pk>\d+)/$', views.RemoveFromCartView.as_view(), name="remove_from_cart_view"),
]

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^kontakt/', views.ContactView.as_view(), name='contact'),
    url(r'^faq/', views.FaqView.as_view(), name='faq'),
    url(r'^o-nas/', views.AboutView.as_view(), name='about'),
    url(r'^zamowienia-indywidualne/', views.CustomOrdersView.as_view(), name='custom_orders'),
    url(r'^$', views.HomeView.as_view(), name='home'),
]

swietlny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from news.views import NotFoundView

urlpatterns = [
    url(r'', include('news.urls', namespace="news")),
    url(r'^produkty/', include('products.urls', namespace="products")),
    url(r'^uzytkownicy/', include('users.urls', namespace="users")),
    url(r'^koszyk/', include('cart.urls', namespace="cart")),
    url(r'^zamowienia/', include('orders.urls', namespace="orders")),
    url(r'^admin/', admin.site.urls),
]

handler404 = NotFoundView.as_view()

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models


class Join(models.Model):
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["timestamp"]
        verbose_name = 'Newsletter'
        verbose_name_plural = 'Newsletter'
    
    def __str__(self):
        return self.email
        
class Faq(models.Model):
    question = models.TextField()
    answer = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["timestamp"]
        verbose_name = 'Pytanie i odp.'
        verbose_name_plural = 'Pytania i odpowiedzi'
    
    def __str__(self):
        return self.question
    
    

news/forms.py
from django import forms

from .models import Join

class JoinForm(forms.ModelForm):
    email = forms.EmailField(label='', 
            widget=forms.EmailInput(
                attrs={
                    'placeholder': 'Twój e-mail',
                    'class': 'form-control',
                    'id': 'newsletter-email'
                }))
    class Meta:
        model = Join
        fields = ['email']
        
    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        qs = Join.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError("Podany e-mail jest już w naszej bazie.")
        return email

   
class ContactForm(forms.Form):
    first_name = forms.CharField(
                                required=False, 
                                label="Imię", 
                                widget=forms.TextInput(attrs={
                                                            'class': "form-control",
                                                            'id': 'contact-first-name'
                                                            }
                                                    )
                                )
    last_name = forms.CharField(
                                required=False, 
                                label="Nazwisko", 
                                widget=forms.TextInput(attrs={
                                                            'class': "form-control",
                                                            'id': 'contact-last-name'
                                                            }
                                                    )
                                )
    subject = forms.CharField(
                            label="Temat", 
                            widget=forms.TextInput(attrs={
                                                        'class': "form-control",
                                                        'id': 'contact-subject'
                                                        }
                                                )
                            )
    email = forms.EmailField(
                            label="E-mail", 
                            widget=forms.TextInput(attrs={
                                                        'class': "form-control",
                                                        'id': 'contact-email'
                                                        }
                                                )
                            )
    message = forms.CharField(
                            label="Wiadomość", 
                            widget=forms.Textarea(attrs={
                                                        'class': "form-control",
                                                        'id': 'contact-message'
                                                        }
                                                )
                            )

news/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail

from products.models import Category, Product

from. models import Join, Faq
from .forms import JoinForm, ContactForm


class HomeView(View):
    form = JoinForm
    template = 'news/home.html'

    def get(self, request):
        new_products = Product.active_objects.filter(is_new=True)
        context = {
            'products': new_products,
        }
        return render(request, self.template, context)
        
    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            email = form.cleaned_data.get('email')
            instance.email = email
            instance.save()
            messages.success(request, 'Dziękujemy! Zapisaliśmy Twój e-mail.', extra_tags='newsletter')
            form = self.form()
        else:
            messages.error(request, 'Podany e-mail jest już w naszej bazie!', extra_tags='newsletter')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        

class FaqView(View):
    template = 'news/faq.html'
    
    def get(self, request):
        faq = Faq.objects.all()
        context = {
            'faq': faq
        }
        return render(request, self.template, context)


class ContactView(View):
    form = ContactForm
    template = 'news/contact.html'
    
    def get(self, request):
        contact_form = self.form(None)
        context = {
            'contact_form': contact_form
        }
        return render(request, self.template, context)
        
    def post(self, request):
        contact_form = self.form(request.POST)
        if contact_form.is_valid():
            first_name = contact_form.cleaned_data.get("first_name")
            last_name = contact_form.cleaned_data.get("last_name")
            subject = contact_form.cleaned_data.get("subject")
            email = contact_form.cleaned_data.get("email")
            message = contact_form.cleaned_data.get("message")
            contact_message = "{} {} via {}: {}".format(first_name, last_name, email, message)
            from_mail = settings.EMAIL_HOST_USER
            to_mail = ['dworanowski.adrian@gmail.com']
            
            send_mail(subject, contact_message, from_mail, to_mail, fail_silently=False)
            
            contact_form = self.form(None)
            messages.success(request, 'Wiadomość została wysłana. Dziękujemy!', extra_tags='contact-form')
            
        context = {
            'contact_form': contact_form
        }
        return render(request, self.template, context)


#flat views
class AboutView(View):
    def get(self, request):
        template = 'news/about.html'
        context = {}
        return render(request, template, context)
        
        
class CustomOrdersView(View):
    def get(self, request):
        template = 'news/custom-orders.html'
        context = {}
        return render(request, template, context)


class NotFoundView(View):
    def get(self, request):
        template = '404.html'
        context = {}
        return render(request, template, context)

news/templates/news/about.html
{% extends "base.html" %} {% block head_title %}O nas{% endblock %} {% block content %} {% load staticfiles %}

<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>O nas</li>
            </ul>
        </div>

        <div class="col-md-12">

            <div class="box" id="text-page">
                <h1>O nas</h1>

                <p class="lead">Wszędobylskie „made in china”, krótkie „życie” produktu, nijakość. To wszystko zmotywowało nas do tego by działać. 
                By stworzyć produkty <strong>„made in poland”</strong>, które posłużą latami. Naszym klientom postanowiliśmy podarować wyjątkowe produkty. 
                Zapraszamy do naszego <strong><a href="{% url 'products:category_view' category_slug='bluzy' %}">świetlnego sklepu</a></strong>.
                </p>

                <h3>Oto ja</h3>

                <blockquote>
                    <p>Siena. To ja projektuje, szyje i doprecyzowuje każdą rzecz, jaką Wam proponujemy. </p>
                </blockquote>
                
                <p>Staram się tworzyć rzeczy unikatowe. 
                    Największą inspiracją i zachętą do dalszego działania jest dla mnie zadowolenie każdej osoby, która wybiera #świetlne produkty. 
                </p>
                <img class="img-responsive" src="{% static 'news/img/slider1.jpg' %}">
                <hr>
                <h3>Doświadczenie</h3>
                <p>
                    Pomimo kilkunastoletniego doświadczenia (tak, nie mam już nastu lat) nieustannie doskonale swój warsztat i umiejętności w rzemiośle nitki i igły. Codzień szukam nowych inspiracji by zrealizować siebie…
                </p>

            </div>


        </div>
        <!-- /.col-md-9 -->
    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}

news/templates/news/contact-js.html
<script type="text/javascript">
// ajax contact message send
        $('#contact-button').click(function(event){
            var first_name = $('#contact-first-name').val();
            var last_name = $('#contact-last-name').val();
            var subject = $('#contact-subject').val();
            var email = $('#contact-email').val();
            var message = $('#contact-message').val();
            event.preventDefault();
            
            $.ajax({
                type: 'POST',
                url: '{% url "news:contact" %}',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'first_name': first_name,
                    'last_name': last_name,
                    'subject': subject,
                    'email': email,
                    'message': message
                },
                success: function(data){
                    var result = $(data).find('#content').contents();
                    $('#content').html(result).find('.contact-message-out').hide().slideDown(500);;
                }
            });
        });
        
        
</script>

news/templates/news/contact.html
{% extends "base.html" %} 
{% block head_title %}Kontakt{% endblock %} 
{% block content %} 
{% load staticfiles %}

<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>Kontakt</li>
            </ul>

        </div>

        <div class="col-md-3">
            {% include 'sidebar-sm.html' %}
        </div>

        <div class="col-md-9">


            <div class="box" id="contact">
                <h1>Kontakt</h1>

                <p class="lead">Chcesz się z nami podzielić swoimi przemyśleniami o naszych produktach? Masz pomysł na oryginalny produkt?</p>
                <p>Napisz lub zadzwoń do nas! </p>

                <hr>

                <div class="row">
                    <div class="col-sm-4">
                        <h3><i class="fa fa-map-marker"></i> Siedziba</h3>
                        <p>Czempiń
                            <br>64-020
                            <br>Wielkoposka
                            <br>
                            <strong>Polska</strong>
                        </p>
                    </div>
                    <!-- /.col-sm-4 -->
                    <div class="col-sm-4">
                        <h3><i class="fa fa-phone"></i> Telefon</h3>
                        <p class="text-muted">Numer jest czynny w godzinach 9-17 od poniedziałku do piątku.</p>
                        <p><strong>+33 555 444 333</strong>
                        </p>
                    </div>
                    <!-- /.col-sm-4 -->
                    <div class="col-sm-4">
                        <h3><i class="fa fa-envelope"></i> E-mail</h3>
                        <p class="text-muted">Na e-maile odpisujemy tak szybko, jak jest to możliwe.</p>
                        <ul>
                            <li><strong><a href="mailto:">swietlne@gmail.com</a></strong>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-sm-4 -->
                </div>
                <!-- /.row -->

                <hr>

                <h2>Formularz kontaktowy</h2>

                <form method="POST">
                {% csrf_token %}
                    <div class="contact-message-out">
                        {% for message in messages %} 
                            {% if "contact-form" in message.tags %}
                            <p{% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</p>
                            {% endif %} 
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ contact_form.first_name.errors }}
                                {{ contact_form.first_name.label_tag }}
                                {{ contact_form.first_name }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ contact_form.last_name.errors }}
                                {{ contact_form.last_name.label_tag }}
                                {{ contact_form.last_name }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ contact_form.email.errors }}
                                {{ contact_form.email.label_tag }}
                                {{ contact_form.email }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ contact_form.subject.errors }}
                                {{ contact_form.subject.label_tag }}
                                {{ contact_form.subject }}
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                {{ contact_form.message.errors }}
                                {{ contact_form.message.label_tag }}
                                {{ contact_form.message }}
                            </div>
                        </div>

                        <div class="col-sm-12 text-center">
                            <button type="submit" id="contact-button" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Wyślij wiadomość</button>

                        </div>
                    </div>
                    <!-- /.row -->
                </form>


            </div>


        </div>
        <!-- /.col-md-9 -->
    </div>
    <!-- /.container -->
    {% include 'news/contact-js.html' %} 
</div>
<!-- /#content -->

{% endblock %}

news/templates/news/custom-orders.html
{% extends "base.html" %} {% block head_title %}O nas{% endblock %} {% block content %} {% load staticfiles %}

<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>Zamówienia indywidualne</li>
            </ul>
        </div>

        <div class="col-md-12">

            <div class="box" id="text-page">
                <h1>Zamowienia indywidualne</h1>

                <p class="lead">Chcesz mieć własne oryginalne i niepowtarzalne etui na książkę, plecak, bluzę? Szukasz prezentu dla wyjątkowej osoby? Chcesz wywołać uśmiech na twarzy swojej Mamy, uroczej sąsiadki, szalonego przyjaciela?</p>
                
                <blockquote>
                <p>Jeśli odpowiedź brzmi: <strong>TAK</strong>, to dobrze trafiłeś! To właśnie tu tworzymy unikatowe rzeczy dla wyjątkowych ludzi. 
                <a href="{% url 'news:contact' %}">Opisz nam krótko swoje oczekiwania</a>, a razem na pewno stworzymy coś niezwykłego! Po uszyciu dostaniesz zdjęcia realizacji do ostatecznej akceptacji, tak abyś był usatysfakcjonowany. Pisz śmiało!
                </p>
                </blockquote>
                
                <img class="img-responsive" src="{% static 'news/img/slider2.jpg' %}">
                
                <hr>
                
                <h3>Dodatkowe informacje</h3>

                <ol>
                    <li>Termin realizacji zamówienia: według indywidualnych ustaleń. </li>
                    <li>Przedmioty wykonane na zamówienie indywidualne nie podlegają zwrotom!</li>
                </ol>
                
                <hr>
                
                <h3>Materiały</h3>
                
                <p>Paski, kratka, materiały jednolite. Poniżej znajdziesz przegląd niektórych tkanin, jakie możemy Tobie zaoferować.</p>

            </div>


        </div>
        <!-- /.col-md-9 -->
    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}

news/templates/news/faq.html
{% extends "base.html" %} {% block head_title %}Kontakt{% endblock %} {% block content %} {% load staticfiles %}

<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona główna</a>
                </li>
                <li>FAQ</li>
            </ul>

        </div>

        <div class="col-md-3">
            {% include 'sidebar-sm.html' %}
        </div>

        <div class="col-md-9">


            <div class="box" id="contact">
                <h1>FAQ - najczęściej zadawane pytania</h1>

                <p class="lead">Tutaj odpowiadamy na to o co pytacie najczęściej.</p>
                <p>Nie znalazłeś odpowiedzi na swoje pytanie?. Napisz do nas uzywając <a href="{% url 'news:contact' %}">formularza kontaktowego.</a></p>

                <hr>

                <div class="panel-group" id="accordion">
                    
                    {% for topic in faq %}    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">

                                <a data-toggle="collapse" data-parent="#accordion" href="#faq{{forloop.counter}}">

						{{forloop.counter}}. {{topic.question}}

					    </a>

                            </h4>
                        </div>
                        <div id="faq{{forloop.counter}}" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>{{topic.answer}}</p>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel -->
                    {% endfor %}

                </div>
                <!-- /.panel-group -->


            </div>


        </div>
        <!-- /.col-md-9 -->
    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}

news/templates/news/home.html
{% extends "base.html" %} 
{% block head_title %}Strona główna{% endblock %} 
{% block content %} 
{% load staticfiles %}
<div id="content">
    <div class="container">
        <div class="col-md-12">
            <div id="main-slider">
                <div class="item">
                    <img class="img-responsive" src="{% static 'news/img/slider1.jpg' %}" alt="">
                    <a href="{% url 'news:custom_orders' %}">
                        <div class="slider-outer2">
                            <div class="slider-inner2">Zamówienia indywidualne</div>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <img class="img-responsive" src="{% static 'news/img/slider2.jpg' %}" alt="" >
                    <a href="{% url 'products:search_view' %}">
                        <div class="slider-outer1">
                            <div class="slider-inner1">Popularne</div>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <img class="img-responsive" src="{% static 'news/img/slider3.jpg' %}" alt="">
                </div>
                <div class="item">
                    <img class="img-responsive" src="{% static 'news/img/slider4.jpg' %}" alt="">
                </div>
            </div>
            <!-- /#main-slider -->
        </div>
    </div>

    <!-- *** HOT PRODUCT SLIDESHOW ***
 _________________________________________________________ -->
    <div id="hot">

        <div class="box">
            <div class="container">
                <div class="col-md-12">
                    <h2>Nowości</h2>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="product-slider">
                {% for product in products %}
                <div class="item">
                    <div class="product">
                        <div class="flip-container">
                            <div class="flipper">
                                <div class="front">
                                    <a href="{% url 'products:product_view' pk=product.pk %}">
                                        <img src="{{product.images.0.image.url}}" alt="" class="img-responsive">
                                    </a>
                                </div>
                                <div class="back">
                                    <a href="{% url 'products:product_view' pk=product.pk %}">
                                        <img src="{{product.images.1.image.url}}" alt="" class="img-responsive">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'products:product_view' pk=product.pk %}" class="invisible">
                            <img src="{{product.images.0.image.url}}" alt="" class="img-responsive">
                        </a>
                        <div class="text">
                            <h3><a href="{% url 'products:product_view' pk=product.pk %}">{{product.title}}</a></h3>
                            <p class="price">{{product.price}} zł</p>
                        </div>
                        <!-- /.text -->
                        {% if product.on_sale %}
                        <div class="ribbon sale">
                            <div class="theribbon">OKAZJA</div>
                            <div class="ribbon-background"></div>
                        </div>
                        {% endif %}
                        <!-- /.ribbon -->
                        {% if product.is_new %}
                        <div class="ribbon new">
                            <div class="theribbon">NOWE</div>
                            <div class="ribbon-background"></div>
                        </div>
                        {% endif %}
                        <!-- /.ribbon -->
                    </div>
                    <!-- /.product -->
                </div>
                {% endfor %}
            </div>
            <!-- /.product-slider -->
        </div>
        <!-- /.container -->

    </div>
    <!-- /#hot -->

    <!-- *** HOT END *** -->
</div>
<!-- /#content -->

{% endblock %}

news/templates/news/newsletter-js.html
<script type="text/javascript">
// ajax newsletter sign-up
        $('#newsletter-button').click(function(event){
            $('.newsletter-message').slideUp(500);
            var email = $('#newsletter-email').val();
            event.preventDefault();
            if (email != '' || email != ' ') {
                $.ajax({
                    type: 'POST',
                    url: '{% url "news:home" %}',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'email': email
                    },
                    success: function(data){
                        var result = $(data).find('.newsletter-message').contents();
                        $('.newsletter-message').hide().html(result).slideDown(500);
                    }
                });
            }
        });
        
        
</script>