cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartView.as_view(), name="cart_view"),
    url(r'^dodaj/(?P<pk>\d+)/$', views.AddToCartView.as_view(), name="add_to_cart_view"),
    url(r'^usun/(?P<pk>\d+)/$', views.RemoveFromCartView.as_view(), name="remove_from_cart_view"),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^adres-wysylki/', views.OrderCreateView.as_view(), name='order_create_view'),
    url(r'^potwierdzenie/', views.OrderConfirmView.as_view(), name='order_confirm_view'),
]

swietlny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from news.views import NotFoundView

urlpatterns = [
    url(r'', include('news.urls', namespace="news")),
    url(r'^produkty/', include('products.urls', namespace="products")),
    url(r'^uzytkownicy/', include('users.urls', namespace="users")),
    url(r'^koszyk/', include('cart.urls', namespace="cart")),
    url(r'^zamowienia/', include('orders.urls', namespace="orders")),
    url(r'^admin/', admin.site.urls),
]

handler404 = NotFoundView.as_view()

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views, forms

urlpatterns = [
    url(r'^logowanie/$', views.LoginView.as_view(), name='login'),
    url(r'^rejestracja/$', views.RegisterView.as_view(), name='register'),
    url(r"^wyloguj/$", auth_views.logout_then_login, name="logout"),
    url(r'^profil/$', views.ProfileView.as_view(), name='profile'),
    url(r'^haslo/$', views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^lista-zyczen/$', views.WishlistView.as_view(), name='wishlist'),
    url(r'^zamowienia/(?P<pk>\d+)/$', views.OrderView.as_view(), name="order"),
    url(r'^zamowienia/', views.OrderListView.as_view(), name='order_list'),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

from products.models import Product

STATUS_CHOICES = (
                    ('awaiting', 'Oczekuje na płatność'),
                    ('in_progress', 'W przygotowaniu'),
                    ('sent', 'Wysłano'),
                    ('cancelled', 'Anulowano')
    )


class AcceptedOrderManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super(AcceptedOrderManager, self).get_queryset().filter(accepted=True)


class Order(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=70)
    email = models.EmailField()
    address = models.CharField(max_length=70)
    phone = models.CharField(max_length=15)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    accepted = models.BooleanField(default=False)
    status = models.CharField(choices=STATUS_CHOICES, max_length=70, 
            default='awaiting')
    shipping_total_price = models.DecimalField(max_digits=50, decimal_places=2, default=10.00)
    
    objects = models.Manager()
    accepted_orders = AcceptedOrderManager()
    
    class Meta:
        verbose_name = 'Zamówienie'
        verbose_name_plural = 'Zamówienia'
    
    def __str__(self):
        return "Zamówienie #{}, użytkownik: {}".format(self.pk, self.user)
        
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
        

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, 
            related_name='items')
    product = models.ForeignKey(Product, related_name="order_items")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return "Przedmiot #{}: {}".format(self.pk, self.product)

    def get_cost(self):
        return self.price * self.quantity

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(null=True, blank=True, max_length=70)
    address = models.CharField(null=True, blank=True, max_length=70)
    phone = models.CharField(null=True, blank=True, max_length=15)
    
    class Meta:
        verbose_name = 'Profil użytkownika'
        verbose_name_plural = 'Profile użytkowników'
    
    def __str__(self):
        return self.user.username

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('full_name', 'email', 'address', 'phone')
        labels = {
            'full_name': 'Imię i nazwisko',
            'email': 'E-mail',
            'address': 'Adres do wysyłki',
            'phone': 'Telefon'
        }
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }

orders/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.mail import send_mail
from django.conf import settings

from users.models import UserProfile
from cart.cart import Cart
from .models import Order, OrderItem
from .forms import OrderCreateForm


class OrderCreateView(View):
    def get(self, request):
        cart = Cart(request)
        template = 'orders/order_create.html'
        order_create_form = OrderCreateForm()

        # checking cart for products
        if len(cart) < 1:
            return redirect('cart:cart_view')

        # prepopulate form for logged users
        if request.user.is_authenticated():
            user = request.user
            user_profile = UserProfile.objects.get(user=user)
            email = user.email
            full_name = user_profile.full_name
            address = user_profile.address
            phone = user_profile.phone
            data = {
                'email': email,
                'full_name': full_name,
                'address': address,
                'phone': phone
            }
            order_create_form = OrderCreateForm(initial=data)

        context = {
            'order_create_form': order_create_form
        }
        return render(request, template, context)

    def post(self, request):
        cart = Cart(request)
        order_create_form = OrderCreateForm(request.POST)
        if order_create_form.is_valid():
            template = 'orders/order_accept.html'
            order = order_create_form.save(commit=False)
            if request.user.is_authenticated():
                order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            context = {
                'order': order
            }
            return render(request, template, context)

        template = 'orders/order_create.html'
        order_create_form = OrderCreateForm()
        context = {
            'order_create_form': order_create_form
        }
        return render(request, template, context)


class OrderConfirmView(View):
    template = 'orders/order_confirm.html'
    
    def get(self, request):
        return redirect('news:home')

    def post(self, request):
        cart = Cart(request)
        order_pk = request.POST.get('order_pk')
        order = Order.objects.get(pk=order_pk)
        order.accepted = True
        order.save()
        cart.clear()

        # Sending e-mail notification to the client and admin
        full_name = order.full_name
        subject = "Potwierdzenie złożenia zamówienia nr {}".format(order.pk)
        email = order.email
        order_items = order.items.all()
        message = "Dziękujemy za złożenie zamówienia. Zamówione przedmioty: \n"
        for item in order_items:
            message += "{}: Ilość: {}\n".format(item.product.title,
                                                item.quantity)
        contact_message = "{} via {}: \n{}".format(full_name, email, message)
        from_mail = settings.EMAIL_HOST_USER
        to_mail = [settings.EMAIL_HOST_USER, order.email]
        send_mail(subject, contact_message, from_mail, to_mail,
                  fail_silently=False)

        context = {
            'order': order
        }
        return render(request, self.template, context)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.core.validators import validate_email
from django.contrib.auth.models import User

from products.models import Product
from orders.models import Order
from cart.forms import CartUpdateProductForm

from .forms import LoginForm, UserForm, UserProfileForm, PasswordChangeCustomForm
from .models import UserProfile


class RegisterView(View):
    template = 'users/register.html'
    
    def get(self, request):
        user_form = UserForm()
        user_profile_form = UserProfileForm()
        context = {
            'user_form': user_form,
            'user_profile_form': user_profile_form
        }
        return render(request, self.template, context)
        
    def post(self, request):
        user_form = UserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and user_profile_form.is_valid():
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            email = user_form.cleaned_data['email']
            user = user_form.save(commit=False)
            user.email = email
            user.set_password(password)
            user.save()
            user_profile = user_profile_form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            
            user = authenticate(username=username, password=password)
            login(request, user)
            
            messages.success(request, 'Utworzono nowe konto!', 
                                extra_tags='register')
            
            user_form = UserForm()
            user_profile_form = UserProfileForm()
        
        context = {
            'user_form': user_form,
            'user_profile_form': user_profile_form
        }
        return render(request, self.template, context)


class LoginView(View):
    template = 'users/register.html'
    
    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        # logging via e-mail address
        try:
            validate_email(username)
            username = User.objects.get(email=username)
        except:
            pass
        
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.META['HTTP_REFERER'])
            else:
                messages.error(request, 
                            'Użytkownik {} został zablokowany'.format(username), 
                            extra_tags='login')
                return redirect('users:register')
        else:
            messages.error(request, 'Błędne hasło i/lub nazwa użytkownika', 
                            extra_tags='login')
            return redirect('users:register')
        
    def get(self, request, *args, **kwargs):
        return redirect('users:register')


class ProfileView(View):
    template = 'users/account.html'
    
    @method_decorator(login_required(login_url='users:register'))
    def get(self, request):
        user = User.objects.get(pk=request.user.pk)
        user_profile = UserProfile.objects.get(user=user)
        data = {
            'full_name': user_profile.full_name, 
            'address': user_profile.address,
            'phone': user_profile.phone,
        }
        user_profile_form = UserProfileForm(None, initial=data)
        user_password_form = PasswordChangeCustomForm(None)
        
        context = {
            'user_profile_form': user_profile_form,
            'user_password_form': user_password_form
        }
        return render(request, self.template, context)
        
    @method_decorator(login_required(login_url='users:register'))    
    def post(self, request):
        user = User.objects.get(pk=request.user.pk)
        user_profile = UserProfile.objects.get(user=user)
        user_profile_form = UserProfileForm(request.POST, instance=user_profile)
        if user_profile_form.is_valid():
            user_profile = user_profile_form.save(commit=False)
            user_profile.user = user
            print(user_profile.address)
            user_profile.save()
        return redirect('users:profile')


class PasswordChangeView(View):
    template = 'users/account.html'
    
    def get(self, request):
        return redirect('users:profile')
    
    @method_decorator(login_required(login_url='users:register')) 
    def post(self, request):
        user_password_form = PasswordChangeCustomForm(user=request.user, data=request.POST)
        if user_password_form.is_valid():
            user = user_password_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Zmiana hasła się powiodła!', 
                            extra_tags='password')
            return redirect('users:profile')
        else:
            messages.error(request, 
                            'Zmiana hasła się nie powiodła! Spróbuj ponownie', 
                            extra_tags='password')
                            
        user = User.objects.get(pk=request.user.pk)
        user_profile = UserProfile.objects.get(user=user)
        user_profile_form = UserProfileForm(request.POST, instance=user_profile)
        
        context = {
            'user_profile_form': user_profile_form,
            'user_password_form': user_password_form
        }
        return render(request, self.template, context)


class WishlistView(View):
    template = 'users/wishlist.html'
    
    @method_decorator(login_required(login_url='users:register'))
    def get(self, request):
        user = User.objects.get(pk=request.user.pk)
        products = Product.objects.filter(wishlist=user)
        cart_form = CartUpdateProductForm()
        context = {
            'products': products,
            'cart_form': cart_form
        }
        return render(request, self.template, context)
        
    @method_decorator(login_required(login_url='users:register'))
    def post(self, request):
        product_pk = request.POST.get("wishlist") or request.POST.get("remove_wishlist")
        user = User.objects.get(pk=request.user.pk)
        product = Product.objects.get(pk=product_pk)
        if request.POST.get("wishlist") is not None:
            if product not in Product.objects.filter(wishlist=user):
                product.wishlist.add(user)
                product.save()
                messages.success(request, 'Produkt {} dodany do listy życzeń!'.format(product), 
                                extra_tags='wishlist')
            else:
                messages.error(request, 'Produkt {} już jest na Twojej liście życzeń!'.format(product), 
                                extra_tags='wishlist')
        elif request.POST.get("remove_wishlist") is not None:
            if product in Product.objects.filter(wishlist=user):
                product.wishlist.remove(user)
                product.save()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])


class OrderListView(View):
    template = 'users/orders.html'

    @method_decorator(login_required(login_url='users:register'))
    def get(self, request):
        user = request.user
        orders = Order.accepted_orders.filter(user=user)
        
        context = {
            'orders': orders
        }
        return render(request, self.template, context)


class OrderView(View):
    template = 'users/order_detail.html'
    
    @method_decorator(login_required(login_url='users:register'))
    def get(self, request, pk):
        order =  get_object_or_404(Order, pk=pk)
        if order.user == request.user:
            context = {
                'order': order
            }
            return render(request, self.template, context)
        else:
            return redirect('users:profile')

users/templates/users/account.html
{% extends "base.html" %} 
{% block head_title %}Moje konto{% endblock %} 
{% block content %} 
{% load staticfiles %}

<div id="content">
    <div class="container">

        <div class="col-md-12">

            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>Moje konto</li>
            </ul>

        </div>

        <div class="col-md-3">
            <!-- *** CUSTOMER MENU ***
 _________________________________________________________ -->
            {% include 'sidebar-account.html' %}

            <!-- *** CUSTOMER MENU END *** -->
        </div>

        <div class="col-md-9">
            <div class="box">
                <h1>Konto użytkownika</h1>
                <p class="lead">Na tej stronie możesz uaktualnić swoje dane oraz zmienić hasło dostępu.</p>
                <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

                <h3>Zmiana hasła</h3>

                <form method="POST" action="{% url 'users:password_change' %}">
                    {% csrf_token %}
                    {% for message in messages %}
                        {% if "password" in message.tags %}
                             <p {% if message.tags %} class="{{message.tags}}" {% endif %}> {{ message }} </p>
                        {% endif %} 
                    {% endfor %}
                    <div class="row">
                    {% for field in user_password_form %} 
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{ field.errors }}
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    </div>

                    <div class="col-sm-12 text-center">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Zapisz hasło</button>
                    </div>
                </form>

                <hr>

                <h3>Dane użytkownika</h3>
                <form method="POST" action="{% url 'users:profile' %}">
                    {% csrf_token %}
                    {% for field in user_profile_form %}
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Zapisz zmiany</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}

users/templates/users/order_detail.html
{% extends "base.html" %} {% block head_title %}Zamówienie nr {{order.pk}}{% endblock %} {% block content %} {% load staticfiles %} {% load mathfilters %}

<div id="content">
    <div class="container">

        <div class="col-md-12">

            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li><a href="{% url 'users:order_list' %}">Moje zamówienia</a>
                </li>
                <li>Zamówienie nr {{order.pk}}</li>
            </ul>

        </div>

        <div class="col-md-3">
            <!-- *** CUSTOMER MENU ***
 _________________________________________________________ -->
            {% include 'sidebar-account.html' %}
            <!-- *** CUSTOMER MENU END *** -->
        </div>

        <div class="col-md-9" id="customer-order">
            <div class="box">
                <h1>Zamówienie nr {{order.pk}}</h1>

                <p class="lead">Zamówienie nr {{order.pk}} zostało złożone <strong>{{order.created.date}}</strong>. Jego status to: <strong>{{order.get_status_display}}</strong>.</p>
                <p class="text-muted">Masz jakieś pytania? Skorzystaj z naszego <a href="{% url 'news:contact' %}">formularza kontaktowego</a> i napisz do nas.</p>

                <hr>

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th colspan="3">Produkt</th>
                                <th>Ilość</th>
                                <th>Cena za 1 szt.</th>
                                <th>Suma</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'products:product_view' pk=item.product.pk %}">
                                        <img src="{{item.product.images.0.image.url}}" alt="{{item.product.title}}">
                                    </a>
                                </td>
                                <td><a href="{% url 'products:product_view' pk=item.product.pk %}">{{item.product.title}}</a>
                                </td>
                                <td></td>
                                <td>{{item.quantity}}</td>
                                <td>{{item.price}} zł</td>
                                <td>{{item.get_cost}} zł</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="5" class="text-right">Podsuma</th>
                                <th>{{order.get_total_cost}} zł</th>
                            </tr>
                            <tr>
                                <th colspan="5" class="text-right">Przesyłka</th>
                                <th>{{order.shipping_total_price}} zł</th>
                            </tr>
                            <tr>
                                <th colspan="5" class="text-right">Suma</th>
                                <th>{{order.get_total_cost|addition:order.shipping_total_price|floatformat:2}} zł</th>
                            </tr>
                        </tfoot>
                    </table>

                </div>
                <!-- /.table-responsive -->

                <div class="row addresses">
                    <div class="col-md-6">
                        <h2>Adres wysyłki:</h2>
                        <p>{{order.full_name}}
                            <br>{{order.address}}
                            <br>
                            <br>Telefon kontaktowy:
                            <br>{{order.phone}}
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}

users/templates/users/orders.html
{% extends "base.html" %} {% block head_title %}Moje zamówienia{% endblock %} {% block content %} {% load staticfiles %}

<div id="content">
    <div class="container">

        <div class="col-md-12">

            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>Moje zamówienia</li>
            </ul>

        </div>

        <div class="col-md-3">
            <!-- *** CUSTOMER MENU ***
 _________________________________________________________ -->
            {% include 'sidebar-account.html' %}

            <!-- *** CUSTOMER MENU END *** -->
        </div>

        <div class="col-md-9" id="customer-orders">
            <div class="box">
                <h1>Moje zamówienia</h1>

                <p class="lead">Historia Twoich zamówień w jednym miejscu.</p>
                <p class="text-muted">Masz jakieś pytania? Skorzystaj z naszego <a href="{% url 'news:contact' %}">formularza kontaktowego</a> i napisz do nas.</p>

                <hr>

                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Nr zamówienia</th>
                                <th>Data</th>
                                <th>Suma</th>
                                <th>Status</th>
                                <th>Opcje</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <th>{{order.pk}}</th>
                                <td>{{order.created.date}}</td>
                                <td>{{order.get_total_cost}} zł</td>
                                <td><span class="label label-info">{{order.get_status_display}}</span>
                                </td>
                                <td><a href="{% url 'users:order' pk=order.pk %}" class="btn btn-primary btn-md">Szczegóły</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}

users/templates/users/wishlist.html
{% extends "base.html" %} 
{% block head_title %}Wishlist - Lista życzeń{% endblock %} 
{% block content %} 
{% load staticfiles %}


<div id="content">
    <div class="container">

        <div class="col-md-12">

            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li>Wishlist - Lista życzeń</li>
            </ul>

        </div>

        <div class="col-md-3">
            <!-- *** CUSTOMER MENU ***
 _________________________________________________________ -->
            {% include 'sidebar-account.html' %}

            <!-- *** CUSTOMER MENU END *** -->
        </div>

        <div class="col-md-9" id="wishlist">

            <div class="box">
                <h1>Wishlist - Lista życzeń</h1>
                <p class="lead">Spodobało Ci się coś, ale chcesz to kupić później? Umieść to na swojej wishliście, aby szybko znaleźć swoje ulubione rzeczy.</p>
            </div>

            <div class="row products">

                {% for product in products %}
                <div class="col-md-3 col-sm-4">
                    <form method="POST" action="{% url 'users:wishlist' %}">
                        {% csrf_token %}
                        <input type="hidden" name="remove_wishlist" value="{{product.pk}}">
                        <button type="submit" class="boxclose"></button>
                    </form>
                    <div class="product">
                        <div class="flip-container">
                            <div class="flipper">
                                <div class="front">
                                    <a href="{% url 'products:product_view' pk=product.pk %}">
                                        <img src="{{product.images.0.image.url}}" alt="" class="img-responsive">
                                    </a>
                                </div>
                                <div class="back">
                                    <a href="{% url 'products:product_view' pk=product.pk %}">
                                        <img src="{{product.images.1.image.url}}" alt="" class="img-responsive">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'products:product_view' pk=product.pk %}" class="invisible">
                            <img src="{{product.images.0.image.url}}" alt="" class="img-responsive">
                        </a>
                        <div class="text">
                            <h3><a href="{% url 'products:product_view' pk=product.pk %}">{{product.title}}</a></h3>
                            <p class="price">{{product.price}} zł</p>
                            <div class="buttons">
                                <a href="{% url 'products:product_view' pk=product.pk %}" class="btn btn-default btn-md">Szczegóły</a>
                                <form method="POST" action="{% url 'cart:add_to_cart_view' pk=product.pk %}">
                                    {% csrf_token %}
                                    <div class="hidden">{{ cart_form }}</div>
                                    <button type="submit" class="btn btn-primary btn-md"><i class="fa fa-shopping-cart"></i>Dodaj do koszyka</a>
                                </form>
                            </div>
                        </div>
                        <!-- /.text -->
                        {% if product.on_sale %}
                        <div class="ribbon sale">
                            <div class="theribbon">OKAZJA</div>
                            <div class="ribbon-background"></div>
                        </div>
                        {% endif %}
                        <!-- /.ribbon -->
                        {% if product.is_new %}
                        <div class="ribbon new">
                            <div class="theribbon">NOWE</div>
                            <div class="ribbon-background"></div>
                        </div>
                        {% endif %}
                        <!-- /.ribbon -->
                    </div>
                    <!-- /.product -->
                </div>
                {% endfor %}
            </div>
            <!-- /.products -->

        </div>
    </div>
    <!-- /.container -->
</div>
<!-- /#content -->

{% endblock %}