cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartView.as_view(), name="cart_view"),
    url(r'^dodaj/(?P<pk>\d+)/$', views.AddToCartView.as_view(), name="add_to_cart_view"),
    url(r'^usun/(?P<pk>\d+)/$', views.RemoveFromCartView.as_view(), name="remove_from_cart_view"),
]

products/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^szukaj/', views.SearchView.as_view(), name='search_view'),
    url(r'^(?P<pk>\d+)/$', views.ProductView.as_view(), name="product_view"),
    url(r'^(?P<category_slug>[\w\-]+)/$', views.CategoryView.as_view(), name="category_view"),
]

swietlny/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from news.views import NotFoundView

urlpatterns = [
    url(r'', include('news.urls', namespace="news")),
    url(r'^produkty/', include('products.urls', namespace="products")),
    url(r'^uzytkownicy/', include('users.urls', namespace="users")),
    url(r'^koszyk/', include('cart.urls', namespace="cart")),
    url(r'^zamowienia/', include('orders.urls', namespace="orders")),
    url(r'^admin/', admin.site.urls),
]

handler404 = NotFoundView.as_view()

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment


# Category
class Category(models.Model):
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    class Meta:
        verbose_name = 'Kategoria'
        verbose_name_plural = 'Kategorie'
    
    def __str__(self):
        return self.title
    
    @property
    def products_count(self):
        products = Product.active_objects.filter(categories=self)
        return len(products)
        
        
# Product
class ActiveProductManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super(ActiveProductManager, self).get_queryset().filter(active=True)
  

class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    material = models.TextField(blank=True, null=True)
    size = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    active = models.BooleanField(default=True)
    is_new = models.BooleanField(default=False)
    on_sale = models.BooleanField(default=False)
    best_buy = models.BooleanField(default=False)
    wishlist = models.ManyToManyField(User, blank=True)
    categories = models.ManyToManyField('Category')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    objects = models.Manager()
    active_objects =  ActiveProductManager()
    
    class Meta:
        ordering = ["title"]
        verbose_name = 'Product'
        verbose_name_plural = 'Produkty'
    
    def __str__(self):
        return self.title
    
    @property    
    def images(self):
        images = ProductImage.objects.filter(product=self)
        return images
    
    def get_absolute_url(self):
        return reverse('products:product_view', args=[str(self.pk)])
    
    @property  
    def content_type(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return content_type
        
    def comments(self):
        comments = Comment.objects.filter(object_id=self.pk)
        return comments


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField()
    
    class Meta:
        verbose_name = 'Zdjęcie produktu'
        verbose_name_plural = 'Zdjęcia produktów'
    
    def __str__(self):
        return self.product.title

products/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect

from cart.forms import CartUpdateProductForm
from comments.forms import CommentCreateForm
from comments.models import Comment

from .models import Product, Category


class CategoryView(View):
    template = 'products/category.html'
    
    def get(self, request, category_slug):
        category = Category.objects.get(slug=category_slug)
        products = Product.active_objects.filter(categories=category)
        
        try:
            request.session['num_filter'] = request.GET['num']
            request.session['sort_by'] = request.GET['sort_by']
        except:
            pass
        
        num_filter = request.session.get('num_filter') or 9
        sort_by = request.session.get('sort_by') or 'title'
        
        cart_form = CartUpdateProductForm()
        
        paginator = Paginator(products, num_filter)
        page = request.GET.get('page')
        
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            products = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            products = paginator.page(paginator.num_pages)
        
        context = {
            'products': products,
            'category': category,
            'sort_by': sort_by,
            'num_filter': num_filter,
            'cart_form': cart_form
        }
        return render(request, self.template, context)


class ProductView(View):
    template = 'products/product.html'
    
    def get(self, request, pk):
        product = Product.active_objects.get(pk=pk)
        cart_form = CartUpdateProductForm()
        comments = product.comments().filter(comment_parent=None)
        data = {
            'content_type': product.content_type,
            'object_id': product.pk,
        }
        comment_create_form = CommentCreateForm(None, initial=data)
        context = {
            'product': product,
            'comments': comments,
            'cart_form': cart_form,
            'comment_create_form': comment_create_form
        }
        return render(request, self.template, context)
        
    def post(self, request, pk):
        comment_create_form = CommentCreateForm(request.POST)
        print(comment_create_form)
        
        if comment_create_form.is_valid():
            comment_username = comment_create_form.cleaned_data.get('comment_username')
            comment_body = comment_create_form.cleaned_data.get('comment_body')
            c_type = comment_create_form.cleaned_data.get('content_type').lower()
            content_type = ContentType.objects.get(model=c_type)
            object_id = comment_create_form.cleaned_data.get('object_id')
            comment_parent = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                comment_parent = Comment.objects.get(pk=parent_id)
            new_comment = Comment.objects.create(
                comment_username=comment_username,
                comment_body=comment_body,
                comment_parent=comment_parent,
                content_type=content_type,
                object_id=object_id
                )
            return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
        return redirect('news:home')

        
class SearchView(View):
    template = 'products/search.html'

    def get(self, request):
        query = request.GET.get('q')
        
        try:
            request.session['num_filter'] = request.GET['num']
            request.session['sort_by'] = request.GET['sort_by']
        except:
            pass
        
        num_filter = request.session.get('num_filter') or 9
        sort_by = request.session.get('sort_by') or 'title'
        
        cart_form = CartUpdateProductForm()
        if query:
            products_all = Product.active_objects.filter(
                                                        Q(title__icontains=query) | 
                                                        Q(description__icontains=query)
                                                        ).distinct()
        else:
            # display only most populars products if there's no query
            products_all = Product.active_objects.filter(best_buy=True)

        paginator = Paginator(products_all, num_filter)
        page = request.GET.get('page')    

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            products = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            products = paginator.page(paginator.num_pages)
        context = {
            'products': products,
            'products_all': products_all,
            'sort_by': sort_by,
            'num_filter': num_filter,
            'cart_form': cart_form
        }
        return render(request, self.template, context)

products/templates/products/category-js.html
<script type="text/javascript">
    $('#filter-button-category').click(function(event) {
        var num = $('select[name="num"]').val();
        var sort_by = $('select[name="sort_by"]').val();
        event.preventDefault();
        $.ajax({
            type: 'GET',
            url: '{% url "products:category_view" category_slug=category.slug %}',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'num': num,
                'sort_by': sort_by
            },
            success: function(data) {
                var result = $(data).find("#content");
                $('.all').html(result);
            },
            error: function(data) {
                console.log('error');
            }
        });
    });
</script>

products/templates/products/category.html
{% extends 'base.html' %}
{% block head_title %}Sklep - {{category.title}}
{% endblock %} 
{% block content %} 
{% load staticfiles %}
{% load mathfilters %}

<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona główna</a>
                </li>
                <li id="category-title">{{category.title}}</li>
            </ul>
        </div>

        <div class="col-md-3">
            {% include 'sidebar.html' %}
        </div>

        <div class="col-md-9">
            <div class="box">
                <h1>{{category.title}}</h1>
                <p>{{category.description}}</p>
            </div>

            <div class="box info-bar">
                <div class="row">
                    <div class="col-sm-12 col-md-3 products-showing">
                        Pokazuje
                        <strong>
                            {% if products %}
                            {{ products.end_index|addition:1|sub:products.start_index }}
                            {% else %}
                            0
                            {% endif %}
                        </strong> z <strong>{{category.products_count}}</strong> produktów
                    </div>

                    <div class="col-sm-12 col-md-9 text-center products-number-sort">
                        <div class="row">
                            <form class="form-inline">
                                <div class="col-md-6 col-sm-6">
                                    <div class="products-number">
                                        <strong>Pokaż</strong>
                                        <select name="num" class="form-control">
                                                    <option value="9" {% if num_filter == '9' %} selected {% endif %}>9</option>
                                                    <option value="12" {% if num_filter == '12' %} selected {% endif %}>12</option>
                                                </select>
                                        <span>produktów</span>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="products-number">
                                        <strong>Sortuj po</strong>
                                        <select name="sort_by" class="form-control">
                                                    <option value="price" {% if sort_by == 'price' %} selected {% endif %}>cenie</option>
                                                    <option value="title" {% if sort_by == 'title' %} selected {% endif %}>nazwie</option>
                                                </select>
                                        <button class="btn btn-primary" id="filter-button-category" type="submit">Pokaż</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row products">
                {% for product in products|dictsort:sort_by %}
                <div class="col-md-4 col-sm-6">
                    <div class="product">
                        <div class="flip-container">
                            <div class="flipper">
                                <div class="front">
                                    <a href="{% url 'products:product_view' pk=product.pk %}">
                                        <img src="{{product.images.0.image.url}}" alt="{{product.title}}" class="img-responsive">
                                    </a>
                                </div>
                                <div class="back">
                                    <a href="{% url 'products:product_view' pk=product.pk %}">
                                        <img src="{{product.images.1.image.url}}" alt="{{product.title}}" class="img-responsive">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'products:product_view' pk=product.pk %}" class="invisible">
                            <img src="{{product.images.0.image.url}}" alt="{{product.title}}" class="img-responsive">
                        </a>
                        <div class="text">
                            <h3><a href="{% url 'products:product_view' pk=product.pk %}">{{product.title}}</a></h3>
                            <p class="price">{{product.price}} zł</p>
                            <div class="buttons">
                                <a href="{% url 'products:product_view' pk=product.pk %}" class="btn btn-default btn-md">Szczegóły</a>
                                <form method="POST" action="{% url 'cart:add_to_cart_view' pk=product.pk %}">
                                    {% csrf_token %}
                                    <div class="hidden">{{ cart_form }}</div>
                                    <button type="submit" class="btn btn-primary btn-md"><i class="fa fa-shopping-cart"></i>Dodaj do koszyka</a>
                                </form>
                            </div>
                            
                        </div>
                        <!-- /.text -->
                        {% if product.on_sale %}
                        <div class="ribbon sale">
                            <div class="theribbon">OKAZJA</div>
                            <div class="ribbon-background"></div>
                        </div>
                        {% endif %}
                        <!-- /.ribbon -->
                        {% if product.is_new %}
                        <div class="ribbon new">
                            <div class="theribbon">NOWE</div>
                            <div class="ribbon-background"></div>
                        </div>
                        {% endif %}
                        <!-- /.ribbon -->
                    </div>
                    <!-- /.product -->
                </div>
                {% endfor %}

            </div>
            <!-- /.products -->

            <div class="pages">

                <ul class="pagination">
                    {% if products.has_previous %}
                    <li><a href="?page={{products.previous_page_number}}">&laquo;</a> {% endif %}
                    </li>
                    {% for pag in products.paginator.page_range %} {% if products.number == pag %}
                    <li class="active"><a href="#">{{ products.number }}</a>
                    </li>
                    {% else %}
                    <li><a href="?page={{pag}}">{{ pag }}</a>
                    </li>
                    {% endif %} {% endfor %} {% if products.has_next %}
                    <li><a href="?page={{products.next_page_number}}">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
        <!-- /.col-md-9 -->
    </div>
    <!-- /.container -->
   {% include 'products/category-js.html' %} 
    
</div>

<!-- /#content -->

{% endblock %}

products/templates/products/product-js.html
<script type="text/javascript">

(function(){
    $('.answer-form').hide()

    $('.reply').click(function(event){
        event.preventDefault();
        $(this).parents(':eq(2)').next('.answer-form').slideToggle(500);
    });
})();
</script>

products/templates/products/product.html
{% extends "base.html" %} {% block head_title %}Sklep - {{product.title}}{% endblock %} {% block content %} {% load staticfiles %}
<div id="content">
    <div class="container">

        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'news:home' %}">Strona domowa</a>
                </li>
                <li><a href="{% url 'products:category_view' category_slug=product.categories.all.0.slug %}">{{product.categories.all.0}}</a>
                </li>
                <li>{{product.title}}</li>
            </ul>

        </div>

        <div class="col-md-3">
            {% include 'sidebar.html' %}
        </div>

        <div class="col-md-9">

            <div class="row" id="productMain">
                <div class="col-sm-6">
                    <div id="mainImage">
                        <img src="{{product.images.0.image.url}}" alt="" class="img-responsive">
                    </div>

                    {% if product.on_sale %}
                    <div class="ribbon sale">
                        <div class="theribbon">OKAZJA</div>
                        <div class="ribbon-background"></div>
                    </div>
                    {% endif %}
                    <!-- /.ribbon -->
                    {% if product.is_new %}
                    <div class="ribbon new">
                        <div class="theribbon">NOWE</div>
                        <div class="ribbon-background"></div>
                    </div>
                    {% endif %}
                    <!-- /.ribbon -->

                </div>
                <div class="col-sm-6">
                    <div class="box">
                        <h1 class="text-center">{{product.title}}</h1>
                        <p class="goToDescription"><a href="#details" class="scroll-to">Zobacz szczegóły</a>
                        </p>
                        <p class="price">{{product.price}} zł</p>
                        {% for message in messages %} {% if "wishlist" in message.tags %}
                        <p{% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</p>
                            {% endif %} {% endfor %}
                            <div class="buttons">
                                <form method="POST" class="inline" action="{% url 'cart:add_to_cart_view' pk=product.pk %}">
                                    {% csrf_token %}
                                    <div class="hidden">{{ cart_form }}</div>
                                    <button type="submit" class="btn btn-primary btn-md"><i class="fa fa-shopping-cart"></i>Dodaj do koszyka</a>
                            </form>
                            <form method="POST" action="{% url 'users:wishlist' %}">
                                {% csrf_token %}
                                <input type="hidden" name="wishlist" value="{{product.pk}}">
                                <button type="submit" class="btn btn-default btn-md"><i class="fa fa-heart"></i> Dodaj do wishlisty</button>
                                </form>
                            </div>
                    </div>

                    <div class="row" id="thumbs">
                        {% for image in product.images %}
                        <div class="col-xs-4">
                            <a href="{{image.image.url}}" class="thumb">
                                <img src="{{image.image.url}}" alt="" class="img-responsive">
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>

            </div>


            <div class="box" id="details">
                <h4>Opis</h4>
                <p>{{product.description}}</p>
                <h4>Materiał i pielęgnacja</h4>
                <p>{{product.material}}</p>
                <h4>Rozmiar</h4>
                <p>{{product.size}}</p>

                <blockquote>
                    <p><em>{{product.categories.all.0.description}}</em>
                    </p>
                </blockquote>

                <hr>
                <div class="social">
                    <h4>Podoba Ci się? Pochwal się znajomym!</h4>
                    <p>
                        <a href="#" class="external facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
                        <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                    </p>
                </div>

            </div>
            <div class="box">
                <div id="comments" data-animate="fadeInUp">
                    <h3>Komentarze</h3>
                    {% for comment in comments %}
                    <div class="row comment">
                        <div class="col-sm-12 col-md-12">
                            <h5 class="pull"><strong>{{comment.comment_username}}</strong></h5>
                            <p class="posted"><i class="fa fa-clock-o"></i> {{comment.timestamp}}</p>
                            <p>{{comment.comment_body}}</p>
                            <p class="p-reply"><a class="reply" href="#"><i class="fa fa-reply"></i> Odpowiedz</a>
                            </p>
                        </div>
                    </div>
                    <div class="answer-form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-2">
                                <div class="form-group">
                                    {{ comment_create_form.comment_username.errors }} 
                                    {{ comment_create_form.comment_username.label_tag }} 
                                    {{ comment_create_form.comment_username }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="form-group">
                                    {{ comment_create_form.comment_body.errors }} 
                                    {{ comment_create_form.comment_body.label_tag }} 
                                    {{ comment_create_form.comment_body }}
                                </div>
                            </div>
                        </div>
                        {{ comment_create_form.content_type }}
                        {{ comment_create_form.object_id }}
                        <input type='hidden' name='parent_id' value='{{comment.id}}'>

                        <div class="row">
                            <div class="col-sm-12 text-right">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-comment-o"></i> Wyślij odpowiedź</button>
                            </div>
                        </div>
                    </form>
                    </div>
                    {% if comment.children %} 
                    {% for child_comment in comment.children %}
                    <div class="row comment">
                        <div class="col-sm-10 col-sm-offset-2 col-md-10 col-md-offset-2">
                            <h5 class="pull"><strong>{{child_comment.comment_username}}</strong></h5>
                            <p class="posted"><i class="fa fa-clock-o"></i> {{child_comment.timestamp}}</p>
                            <p>{{child_comment.comment_body}}</p>
                        </div>
                    </div>
                    {% endfor %} 
                    {% endif %}
                    <!-- /.comment -->
                    <hr>
                    {% endfor %}

                </div>
                <!-- /#comments -->

                <div id="comment-form" data-animate="fadeInUp">

                    <h4>Napisz komentarz</h4>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ comment_create_form.comment_username.errors }} {{ comment_create_form.comment_username.label_tag }} {{ comment_create_form.comment_username }}
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    {{ comment_create_form.comment_body.errors }} {{ comment_create_form.comment_body.label_tag }} {{ comment_create_form.comment_body }}
                                </div>
                            </div>
                        </div>
                        {{ comment_create_form.content_type }}
                        {{ comment_create_form.object_id }}

                        <div class="row">
                            <div class="col-sm-12 text-right">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-comment-o"></i> Wyślij komentarz</button>
                            </div>
                        </div>


                    </form>

                </div>
                <!-- /#comment-form -->
            </div>
        </div>
        <!-- /.col-md-9 -->
    </div>
    <!-- /.container -->
    {% include 'products/product-js.html' %} 
</div>
<!-- /#content -->

{% endblock %}

products/templates/products/search-js.html
<script type="text/javascript">
    $('#filter-button-search').click(function(event){
        var q = '{{request.GET.q}}';
        var num = $('select[name="num"]').val();
        var sort_by = $('select[name="sort_by"]').val();
        event.preventDefault();
        
        // ajax for search view
        $.ajax({
            type: 'GET',
            url: '{% url "products:search_view" %}',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'q': q,
                'num': num,
                'sort_by': sort_by
            },
            success: function(data){
                var result = $(data).find("#content");
                $('.all').html(result);
            },
            error: function(data){
                console.log('error');
            }
        }); 
    });
</script>